{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "c39f9cbc",
   "metadata": {},
   "source": [
    "### This notebook will contain the loading of the datasets, and tie together the different parts of the project"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ae572cff",
   "metadata": {},
   "source": [
    "### IMPORTS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0048a912",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from DataLoader import DataLoader\n",
    "from models.CNN import *\n",
    "from models.ffn import *\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from models.CointegrationResidualGenerator import CointegrationResidualGenerator\n",
    "from models.BacktestSharpeEvaluator import BacktestSharpeEvaluator\n",
    "from PortfolioOptimizer import PortfolioOptimizer\n",
    "from TimeSeriesDataSplitter import TimeSeriesDataSplitter\n",
    "from Utility import Utility\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "86c966b7",
   "metadata": {},
   "source": [
    "### Data Preperation\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "d7fdc4ee",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Data loaded successfully from ../data/european_wholesale_electricity_price_data_daily.csv\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Volter\\Documents\\GITHUB REPOSITORIES\\stat3007-deep-learning-project\\src\\DataLoader.py:186: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.\n",
      "  price_matrix = price_matrix.fillna(method=fill_method)\n",
      "c:\\Users\\Volter\\Documents\\GITHUB REPOSITORIES\\stat3007-deep-learning-project\\src\\DataLoader.py:143: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.\n",
      "  price_matrix = price_matrix.fillna(method=fill_method)\n"
     ]
    }
   ],
   "source": [
    "# Initialize the DataLoader with the test data\n",
    "parser = DataLoader(file_path=\"../data/european_wholesale_electricity_price_data_daily.csv\")\n",
    "\n",
    "# Get list of countries\n",
    "all_countries_list = parser.get_country_list()\n",
    "small_counties_list = all_countries_list[:5]\n",
    "\n",
    "# Define the total time range\n",
    "train_time_range = \"2015-01-01,2024-01-01\"\n",
    "\n",
    "# Define the window size and stride\n",
    "one_window_days = 365\n",
    "window_stride_days = 5\n",
    "\n",
    "# Get the rolling window of the test data\n",
    "x_data = parser.get_price_matrix_rolling_window(\n",
    "    one_window_days=one_window_days,\n",
    "    window_stride_days=window_stride_days,\n",
    "    time_range=train_time_range,\n",
    "    countries=all_countries_list,\n",
    "    fill_method=\"ffill\",\n",
    ")\n",
    "\n",
    "# -----------------------------------------------------\n",
    "\n",
    "# Get the price matrix for the training/testing/validation data\n",
    "price_matrix = parser.get_price_matrix(\n",
    "    time_range=train_time_range,\n",
    "    countries=all_countries_list,\n",
    "    fill_method=\"ffill\",\n",
    ")\n",
    "\n",
    "# ------------------------------------------------------\n",
    "# Get the returns matrix\n",
    "returns_tr = price_matrix.pct_change().dropna()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "acb2ee39",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "Skipping due to error: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required by LinearRegression.\n",
      "The cumulative residual window size exceeds the available data.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The cumulative residual window size exceeds the available data.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The cumulative residual window size exceeds the available data.\n",
      "The cumulative residual window size exceeds the available data.\n",
      "The cumulative residual window size exceeds the available data.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n"
     ]
    }
   ],
   "source": [
    "# Get the rolling window of the training data\n",
    "x_cumulative_residuals, y_next_day_returns = Utility.process_training_data(\n",
    "    x_tr_data=x_data,\n",
    "    returns=returns_tr,\n",
    "    cumulative_residual_window=30\n",
    ")\n",
    "\n",
    "# Convert x_tr_cumulative_residuals to a numpy array\n",
    "x_cumulative_residuals = np.array(x_cumulative_residuals)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "c011bd2f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "------------------------------------\n",
      "x_cumulative_residuals shape: (111779, 31, 30)\n",
      "x_cumulative_residuals type: <class 'numpy.ndarray'>\n",
      "y_next_day_returns shape: (111779, 31)\n",
      "y_next_day_returns type: <class 'pandas.core.frame.DataFrame'>\n"
     ]
    }
   ],
   "source": [
    "# # Print the shape of the cnn_input_array\n",
    "# print(f\"cnn_input_array shape: {cnn_input_array.shape}\")\n",
    "# # Print the type of the cnn_input_array\n",
    "# print(f\"cnn_input_array type: {type(cnn_input_array)}\")\n",
    "\n",
    "# # Print the shape of next_day_returns\n",
    "# print(f\"next_day_returns shape: {next_day_returns.shape}\")\n",
    "# # Print the type of next_day_returns\n",
    "# print(f\"next_day_returns type: {type(next_day_returns)}\")\n",
    "\n",
    "print(\"------------------------------------\")\n",
    "\n",
    "# Print the shape of a3_0\n",
    "print(f\"x_cumulative_residuals shape: {x_cumulative_residuals.shape}\")\n",
    "# Print the type of a3_0\n",
    "print(f\"x_cumulative_residuals type: {type(x_cumulative_residuals)}\")\n",
    "\n",
    "# Print the shape of a3_1\n",
    "print(f\"y_next_day_returns shape: {y_next_day_returns.shape}\")\n",
    "# Print the type of a3_1\n",
    "print(f\"y_next_day_returns type: {type(y_next_day_returns)}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "382150bc",
   "metadata": {},
   "source": [
    "### CNN + FFN (Ablation study)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c729c902",
   "metadata": {},
   "source": [
    "#### Sharpe ratio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "8397151f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def sharpe_ratio_loss(returns, risk_free_rate=0.0):\n",
    "    \"\"\"\n",
    "    Custom loss function to maximize the Sharpe Ratio.\n",
    "    Args:\n",
    "        returns (torch.Tensor): Predicted returns\n",
    "        risk_free_rate (float): Risk-free rate for Sharpe calculation\n",
    "    Returns:\n",
    "        torch.Tensor: Negative Sharpe Ratio (to minimize)\n",
    "    \"\"\"\n",
    "    excess_returns = returns - risk_free_rate\n",
    "    mean_excess = torch.mean(excess_returns)\n",
    "    std_excess = torch.std(excess_returns, unbiased=False) + 1e-6  # epsilon for stability\n",
    "    sharpe_ratio = mean_excess / std_excess\n",
    "    return -sharpe_ratio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5ab69198",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Data loaded successfully from ../data/european_wholesale_electricity_price_data_daily.csv\n",
      "\n",
      "--- List of Countries ---\n",
      "['Austria', 'Belgium', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'United Kingdom', 'Bulgaria', 'Serbia', 'Croatia', 'Montenegro', 'North Macedonia', 'Ireland']\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Volter\\Documents\\GITHUB REPOSITORIES\\stat3007-deep-learning-project\\src\\DataLoader.py:143: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.\n",
      "  price_matrix = price_matrix.fillna(method=fill_method)\n",
      "c:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py:393: RuntimeWarning: invalid value encountered in log\n",
      "  result = func(self.values, **kwargs)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train dataset shape: (230, 31, 30), Train next day returns shape: (230, 31)\n",
      "Validation dataset shape: (49, 31, 30), Validation next day returns shape: (49, 31)\n",
      "Test dataset shape: (50, 31, 30), Test next day returns shape: (50, 31)\n",
      "Training with filters: 8, filter size: 3, hidden dim: 64\n",
      "\n",
      "Final Sharpe Ratio on Validation Set: -0.1906\n",
      "Training with filters: 8, filter size: 3, hidden dim: 128\n",
      "\n",
      "Final Sharpe Ratio on Validation Set: -0.2421\n",
      "Training with filters: 8, filter size: 5, hidden dim: 64\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mKeyboardInterrupt\u001b[39m                         Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[7]\u001b[39m\u001b[32m, line 131\u001b[39m\n\u001b[32m    119\u001b[39m optimizer = PortfolioOptimizer(train_dataset, \n\u001b[32m    120\u001b[39m                                train_next_day_returns, \n\u001b[32m    121\u001b[39m                                val_dataset,\n\u001b[32m   (...)\u001b[39m\u001b[32m    127\u001b[39m                                filter_size=filter_size,\n\u001b[32m    128\u001b[39m                                hidden_dim=hidden_dim)\n\u001b[32m    130\u001b[39m \u001b[38;5;66;03m# Train the model\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m131\u001b[39m _, portfolio_returns = \u001b[43moptimizer\u001b[49m\u001b[43m.\u001b[49m\u001b[43mtrain\u001b[49m\u001b[43m(\u001b[49m\u001b[43mverbose\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m)\u001b[49m \u001b[38;5;66;03m# The final sharpe should be from the validation set\u001b[39;00m\n\u001b[32m    133\u001b[39m \u001b[38;5;66;03m# Evaluate the model on the validation set\u001b[39;00m\n\u001b[32m    134\u001b[39m val_sharpe, _ = optimizer.evaluate_final()\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\Volter\\Documents\\GITHUB REPOSITORIES\\stat3007-deep-learning-project\\src\\PortfolioOptimizer.py:183\u001b[39m, in \u001b[36mPortfolioOptimizer.train\u001b[39m\u001b[34m(self, verbose)\u001b[39m\n\u001b[32m    180\u001b[39m     loss = \u001b[38;5;28mself\u001b[39m.sharpe_ratio_loss(portfolio_returns)\n\u001b[32m    182\u001b[39m     \u001b[38;5;66;03m# Backward pass and optimization\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m183\u001b[39m     \u001b[43mloss\u001b[49m\u001b[43m.\u001b[49m\u001b[43mbackward\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    184\u001b[39m     \u001b[38;5;28mself\u001b[39m.optimizer.step()\n\u001b[32m    186\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m epoch % \u001b[32m10\u001b[39m == \u001b[32m0\u001b[39m \u001b[38;5;129;01mand\u001b[39;00m verbose:\n\u001b[32m    187\u001b[39m     \u001b[38;5;66;03m# Evaluate Sharpe ratio for every 10th epoch\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\torch\\_tensor.py:581\u001b[39m, in \u001b[36mTensor.backward\u001b[39m\u001b[34m(self, gradient, retain_graph, create_graph, inputs)\u001b[39m\n\u001b[32m    571\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m has_torch_function_unary(\u001b[38;5;28mself\u001b[39m):\n\u001b[32m    572\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m handle_torch_function(\n\u001b[32m    573\u001b[39m         Tensor.backward,\n\u001b[32m    574\u001b[39m         (\u001b[38;5;28mself\u001b[39m,),\n\u001b[32m   (...)\u001b[39m\u001b[32m    579\u001b[39m         inputs=inputs,\n\u001b[32m    580\u001b[39m     )\n\u001b[32m--> \u001b[39m\u001b[32m581\u001b[39m \u001b[43mtorch\u001b[49m\u001b[43m.\u001b[49m\u001b[43mautograd\u001b[49m\u001b[43m.\u001b[49m\u001b[43mbackward\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    582\u001b[39m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mgradient\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mretain_graph\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcreate_graph\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43minputs\u001b[49m\u001b[43m=\u001b[49m\u001b[43minputs\u001b[49m\n\u001b[32m    583\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\torch\\autograd\\__init__.py:347\u001b[39m, in \u001b[36mbackward\u001b[39m\u001b[34m(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)\u001b[39m\n\u001b[32m    342\u001b[39m     retain_graph = create_graph\n\u001b[32m    344\u001b[39m \u001b[38;5;66;03m# The reason we repeat the same comment below is that\u001b[39;00m\n\u001b[32m    345\u001b[39m \u001b[38;5;66;03m# some Python versions print out the first line of a multi-line function\u001b[39;00m\n\u001b[32m    346\u001b[39m \u001b[38;5;66;03m# calls in the traceback and some print out the last line\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m347\u001b[39m \u001b[43m_engine_run_backward\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    348\u001b[39m \u001b[43m    \u001b[49m\u001b[43mtensors\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    349\u001b[39m \u001b[43m    \u001b[49m\u001b[43mgrad_tensors_\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    350\u001b[39m \u001b[43m    \u001b[49m\u001b[43mretain_graph\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    351\u001b[39m \u001b[43m    \u001b[49m\u001b[43mcreate_graph\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    352\u001b[39m \u001b[43m    \u001b[49m\u001b[43minputs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    353\u001b[39m \u001b[43m    \u001b[49m\u001b[43mallow_unreachable\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m    354\u001b[39m \u001b[43m    \u001b[49m\u001b[43maccumulate_grad\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m    355\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\Volter\\anaconda3\\envs\\DeepLearningSTAT7007\\Lib\\site-packages\\torch\\autograd\\graph.py:825\u001b[39m, in \u001b[36m_engine_run_backward\u001b[39m\u001b[34m(t_outputs, *args, **kwargs)\u001b[39m\n\u001b[32m    823\u001b[39m     unregister_hooks = _register_logging_hooks_on_whole_graph(t_outputs)\n\u001b[32m    824\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m825\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mVariable\u001b[49m\u001b[43m.\u001b[49m\u001b[43m_execution_engine\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrun_backward\u001b[49m\u001b[43m(\u001b[49m\u001b[43m  \u001b[49m\u001b[38;5;66;43;03m# Calls into the C++ engine to run the backward pass\u001b[39;49;00m\n\u001b[32m    826\u001b[39m \u001b[43m        \u001b[49m\u001b[43mt_outputs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\n\u001b[32m    827\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m  \u001b[38;5;66;03m# Calls into the C++ engine to run the backward pass\u001b[39;00m\n\u001b[32m    828\u001b[39m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[32m    829\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m attach_logging_hooks:\n",
      "\u001b[31mKeyboardInterrupt\u001b[39m: "
     ]
    }
   ],
   "source": [
    "\n",
    "# MAIN FUNCTION\n",
    "### -------------- PARSING DATA -------------- ###\n",
    "parser = DataLoader(file_path=\"../data/european_wholesale_electricity_price_data_daily.csv\")\n",
    "\n",
    "# Get list of countries\n",
    "print(\"\\n--- List of Countries ---\")\n",
    "all_countries_list = parser.get_country_list()\n",
    "print(all_countries_list)\n",
    "\n",
    "# Get daily price matrix for all countries for the entire year 2021\n",
    "price_matrix = parser.get_price_matrix(\n",
    "    time_range=\"2021-01-01,2021-12-31\",\n",
    "    countries=all_countries_list,\n",
    "    fill_method=\"ffill\"\n",
    ")\n",
    "\n",
    "# Get the raw daily returns for the price matrix\n",
    "returns = price_matrix.pct_change().dropna()\n",
    "\n",
    "\n",
    "\n",
    "### -------------- COINTEGRATION RESIDUALS -------------- ###\n",
    "# Create an instance of the CointegrationResidualGenerator\n",
    "residual_generator = CointegrationResidualGenerator(price_matrix)\n",
    "\n",
    "residual_generator.compute_all_asset_residuals()\n",
    "\n",
    "# Get residuals\n",
    "asset_residuals = residual_generator.get_asset_residuals()\n",
    "\n",
    "# Get the input for CNN\n",
    "# cnn_input contains a set of 329 data samples, each sample represents 30-day cumulative residuals for the 31 countries\n",
    "cumulative_residual_window = 30\n",
    "cnn_input = residual_generator.prepare_cnn_input_from_residuals(window=cumulative_residual_window)\n",
    "\n",
    "# Get the start index of the first 30-day cumulative residuals in the returns DataFrame\n",
    "start_idx_in_returns = returns.index.get_loc(asset_residuals.index[0])\n",
    "num_samples = len(asset_residuals) - cumulative_residual_window + 1\n",
    "next_day_indices = [start_idx_in_returns + i + cumulative_residual_window for i in range(num_samples)]\n",
    "\n",
    "# Get the next-day returns for the corresponding indices\n",
    "# The next-day returns are the returns for the day after the last day of each 30-day window\n",
    "# For example, if the first 30-day window ends on index 0, the next day return is at index 1\n",
    "# If the second 30-day window ends on index 1, the next day return is at index 2, and so on.\n",
    "next_day_returns = returns.iloc[next_day_indices]\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "### -------------- FEED THE 30-DAY CUMULATIVE RESIDUALS OF EVERY COUNTRY TO CNN+FFN -------------- ###\n",
    "# Transform cnn_input to be compatible with the CNN input shape\n",
    "cnn_input_array = cnn_input.transpose(0, 2, 1) # [samples, features, window]\n",
    "\n",
    "# FILIP'S SECTION: CNN+FFN\n",
    "# Hey Filip, this is the section where you can add your code to train the CNN+FFN model.\n",
    "# cnn_input_array essentially contains 329 training data points, each data point is 30-day cumulative residuals for the 31 countries.\n",
    "# So, for one \"data point\" you would feed the set of 30-day cumulative residuals for every country to the CNN+FFN model.\n",
    "# One data point should result in a set of weights for each of the 31 countries.\n",
    "# Each set of weights is used to calculate one next-day portfolio return.\n",
    "# Repeat this for all 329 data points to get a set of 329 portfolio returns.\n",
    "# You can then use these portfolio returns to calculate the Sharpe ratio\n",
    "# Optimize the CNN+FFN to maximize the Sharpe ratio.\n",
    "\n",
    "# Set the device to GPU if available, otherwise MPS (for Mac silicon) or CPU\n",
    "if torch.cuda.is_available():\n",
    "    device = torch.device(\"cuda\")\n",
    "elif torch.backends.mps.is_available():\n",
    "    device = torch.device(\"mps\")\n",
    "else:\n",
    "    device = torch.device(\"cpu\")\n",
    "\n",
    "torch.manual_seed(1)  # For reproducibility\n",
    "\n",
    "# Create the PortfolioOptimizer instance and train the model\n",
    "# NOTE: We need to have some validation data to evaluate the model performance\n",
    "# otherwise we will be overfitting the model to the training data\n",
    "\n",
    "# Grid search for hyperparameters\n",
    "num_filters = [8, 16, 32]\n",
    "filter_sizes = [3, 5, 7]\n",
    "hidden_dims = [64, 128]\n",
    "\n",
    "# Choose the best hyperparameters based on validation performance\n",
    "best_score = float('-inf')\n",
    "best_params = None\n",
    "\n",
    "# Training and validation split\n",
    "# 70% training, 15% validation, 15% testing\n",
    "# Note: The test set is not used in the training process, but it can be used ONCE to evaluate the final model performance\n",
    "# The validation set is used to tune the hyperparameters and avoid overfitting\n",
    "\"\"\"\n",
    "train_dataset = cnn_input_array[:int(0.7 * len(cnn_input_array))]\n",
    "train_next_day_returns = next_day_returns[:int(0.7 * len(next_day_returns))]\n",
    "\n",
    "val_dataset = cnn_input_array[int(0.7 * len(cnn_input_array)):]\n",
    "val_next_day_returns = next_day_returns[int(0.7 * len(next_day_returns)):]\n",
    "\n",
    "test_dataset = val_dataset[int(0.5 * len(val_dataset)):]\n",
    "test_next_day_returns = val_next_day_returns[int(0.5 * len(val_next_day_returns)):]\n",
    "\"\"\"\n",
    "# datasetSplitter = TimeSeriesDataSplitter(data_x=cnn_input_array, data_y=next_day_returns, train_size=0.7, validation_size=0.15, test_size=0.15)\n",
    "datasetSplitter = TimeSeriesDataSplitter(data_x=x_cumulative_residuals, data_y=y_next_day_returns, train_size=0.7, validation_size=0.15, test_size=0.15)\n",
    "(train), (val), (test) = datasetSplitter.split_data()\n",
    "\n",
    "# Unpack the datasets\n",
    "train_dataset, train_next_day_returns = train\n",
    "val_dataset, val_next_day_returns = val\n",
    "test_dataset, test_next_day_returns = test\n",
    "\n",
    "print(f\"Train dataset shape: {train_dataset.shape}, Train next day returns shape: {train_next_day_returns.shape}\")\n",
    "print(f\"Validation dataset shape: {val_dataset.shape}, Validation next day returns shape: {val_next_day_returns.shape}\")\n",
    "print(f\"Test dataset shape: {test_dataset.shape}, Test next day returns shape: {test_next_day_returns.shape}\")\n",
    "\n",
    "for num_filter in num_filters:\n",
    "    for filter_size in filter_sizes:\n",
    "        for hidden_dim in hidden_dims:\n",
    "                print(f\"Training with filters: {num_filter}, filter size: {filter_size}, hidden dim: {hidden_dim}\")\n",
    "                \n",
    "                # Initialize the PortfolioOptimizer\n",
    "                optimizer = PortfolioOptimizer(train_dataset, \n",
    "                                               train_next_day_returns, \n",
    "                                               val_dataset,\n",
    "                                               val_next_day_returns,\n",
    "                                               batch_size=1000, \n",
    "                                               num_epochs=1000, \n",
    "                                               num_filters=num_filter, \n",
    "                                               device=device, \n",
    "                                               filter_size=filter_size,\n",
    "                                               hidden_dim=hidden_dim)\n",
    "                \n",
    "                # Train the model\n",
    "                _, portfolio_returns = optimizer.train(verbose=False) # The final sharpe should be from the validation set\n",
    "\n",
    "                # Evaluate the model on the validation set\n",
    "                val_sharpe, _ = optimizer.evaluate_final()\n",
    "                if val_sharpe > best_score:\n",
    "                    best_score = val_sharpe\n",
    "                    best_params = (num_filter, filter_size, hidden_dim)\n",
    "                    best_portfolio_returns = portfolio_returns\n",
    "    \n",
    "print(f\"Best parameters: {best_params} with Sharpe Ratio on Validation Set: {best_score}\")\n",
    "\n",
    "### -------------- GET THE WEIGHTS OUTPUTTED FROM CNN+FFN -------------- ###\n",
    "# Initializing the Sharpe ratio evaluator\n",
    "#evaluator = BacktestSharpeEvaluator()\n",
    "\n",
    "# Get the weight outputted from the CNN+FFN model\n",
    "# One weight for each country\n",
    "#weights = np.array([]) # CHANGE THIS TO THE ACTUAL WEIGHTS OUTPUTTED FROM THE CNN+FFN MODEL\n",
    "\n",
    "# Normalize the weights using L1 normalization\n",
    "# This is done to ensure that the portfolio is dollar-neutral\n",
    "#normalized_weights = evaluator.normalize_weights_l1(weights)\n",
    "\n",
    "# Multiply the normalized weights (vector) with the next-day returns (vector) to get the portfolio return\n",
    "#next_day_portfolio_return = evaluator.compute_portfolio_return(normalized_weights, next_day_returns.iloc[0].values)\n",
    "\n",
    "# Store the next day portfolio return \n",
    "#evaluator.add_return(next_day_portfolio_return)\n",
    "\n",
    "# Repeat the above step for all 329 data points, adding the portfolio returns to the evaluator for each data point\n",
    "\n",
    "# Once all portfolio returns are calculated, you can calculate the Sharpe ratio\n",
    "\n",
    "# Train the model to optimize the Sharpe Ratio\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "DeepLearningSTAT7007",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
